/**
 * Message Stream Handler (messages.upsert)
 * Integrates Moderation, Interactive Callbacks, and Command Routing
 */

const { normalizeMessage } = require('../core/message');
const { handleCommand } = require('./commandHandler');
const { onReplyMap, botSentMessages } = require('../services/cacheService');
const { containsLink, containsWhatsAppLink } = require('../utils/antilink');
const { containsBadWord } = require('../utils/badwords');
const database = require('../database');
const groupService = require('../services/groupService');
const apiService = require('../services/apiService');
const config = require('../config');
const logger = require('../utils/logger');
const { decodeJid } = require('../utils/myfunc');

async function handleMessages(sock, chatUpdate) {
  try {
    if (!chatUpdate || !chatUpdate.messages || chatUpdate.messages.length === 0) return;

    for (const rawMsg of chatUpdate.messages) {
      if (!rawMsg.message) continue;

      // Ignore broadcast status updates
      if (rawMsg.key && rawMsg.key.remoteJid === 'status@broadcast') continue;

      // Ignore messages generated by this bot instance to avoid loops
      if (rawMsg.key?.id && botSentMessages.has(rawMsg.key.id)) continue;

      // Handle fromMe messages: ignore unless selfListen is enabled in configuration
      const isFromMe = Boolean(rawMsg.key?.fromMe);
      const selfListen = Boolean(config.listen?.selfListen || config.wca?.selfListen || config.selfListen);
      if (isFromMe && !selfListen) continue;

      const ctx = await normalizeMessage(sock, rawMsg);
      if (!ctx) continue;

      const { chat, sender, isGroup, text, m, message, quoted } = ctx;

      // 1. Auto-read status / messages
      if (config.autoRead && typeof sock.readMessages === 'function') {
        sock.readMessages([rawMsg.key]).catch(() => {});
      }

      // 2. Auto-typing simulation
      if (config.autoTyping) {
        message.typing(1500).catch(() => {});
      }

      // 3. Group Moderation (Antilink & Antibadword)
      if (isGroup) {
        const groupSettings = database.getGroupSettings(chat);

        // Antilink Check
        if (groupSettings.antilink && (containsWhatsAppLink(text) || containsLink(text))) {
          const isSenderAdmin = await groupService.isUserAdmin(sock, chat, sender);
          if (!isSenderAdmin && !ctx.isOwner && !ctx.isBotAdmin) {
            const isBotAdmin = await groupService.isBotAdmin(sock, chat);
            if (isBotAdmin) {
              await message.unsend(m.key);
              await message.send(`⚠️ @${sender.split('@')[0]}, links are strictly forbidden in this group!`, {
                mentions: [sender]
              });
              return;
            }
          }
        }

        // Antibadword Check
        if (groupSettings.antibadword && containsBadWord(text)) {
          const isSenderAdmin = await groupService.isUserAdmin(sock, chat, sender);
          if (!isSenderAdmin && !ctx.isOwner && !ctx.isBotAdmin) {
            const isBotAdmin = await groupService.isBotAdmin(sock, chat);
            if (isBotAdmin) {
              await message.unsend(m.key);
              await message.send(`⚠️ @${sender.split('@')[0]}, foul language is not allowed here!`, {
                mentions: [sender]
              });
              return;
            }
          }
        }
      }

      // 4. Interactive onReply Callback Handling (GoatBot V2 onReply compatibility)
      if (quoted && quoted.id && onReplyMap.has(quoted.id)) {
        const replyHandler = onReplyMap.get(quoted.id);
        if (replyHandler && typeof replyHandler.callback === 'function') {
          // If the reply handler restricts to original sender
          if (!replyHandler.author || replyHandler.author === sender) {
            try {
              await replyHandler.callback({
                sock,
                message,
                m,
                args: text.trim().split(/\s+/),
                body: text,
                event: ctx,
                replyData: replyHandler.data
              });
              if (replyHandler.once) onReplyMap.delete(quoted.id);
              return;
            } catch (err) {
              logger.error('[ON_REPLY] Error executing callback:', err.message);
            }
          }
        }
      }

      // 5. Route to Command Handler if command parsed
      if (ctx.command) {
        await handleCommand(ctx);
        return;
      }

      // 6. Chatbot AI trigger
      const botJid = decodeJid(sock.user?.id);
      const isMentioned = ctx.mentions && ctx.mentions.includes(botJid);
      const isGroupChatbotOn = isGroup && database.getGroupSettings(chat).chatbot;
      const isPrivateChatbot = !isGroup && text.length > 1;

      if (isMentioned || isGroupChatbotOn || isPrivateChatbot) {
        const cleanPrompt = text.replace(/@[0-9]+/g, '').trim();
        if (cleanPrompt.length > 0) {
          try {
            message.typing(2000).catch(() => {});
            const aiReply = await apiService.getAiResponse(cleanPrompt);
            await message.reply(aiReply);
          } catch (_) {}
        }
      }
    }
  } catch (err) {
    logger.error('[MESSAGE_HANDLER] Unexpected error in messages.upsert:', err.message);
  }
}

module.exports = {
  handleMessages
};
